# Generated by Django 5.2.5 on 2025-09-03 16:57

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber


def normalize_phones(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
    ]



