# Generated by Django 5.2.5 on 2025-10-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_fill_orderitem_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='комментарий менеджера'),
        ),
    ]
