# Generated by Django 5.2.5 on 2025-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_manager_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('electronic', 'Электронно')], db_index=True, default='cash', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
