# Generated by Django 5.2.5 on 2025-11-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_remove_order_latitude_remove_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('electronic', 'Электронно')], db_index=True, max_length=20, verbose_name='способ оплаты'),
        ),
    ]
